version: '3.8'

services:
  maritime-etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: port_state_biosecurity_etl
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./assets:/app/assets
